version: '2.1'
services:
   mysql:
     image: mysql:5.7
     environment:
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_DATABASE=videodb
      - MYSQL_USER=orguser
      - MYSQL_PASSWORD=secret1234
     healthcheck:
      test: mysql --user=videouser --password=secret1234 -e 'show databases;'
      interval: 2s
      timeout: 2s
      retries: 10
   testfrontend:
     image: kvalitetsit/gooioidwsrest:1.1.14
     command:
      - "-config"
      - "/caddy/config.json"
     volumes:
      - ./frontend.json:/caddy/config.json
     ports:
      - 8080:80
   videoapiservice:
     image: kvalitetsit/medcom-video-api:latest
     environment:
      - jdbc_url=jdbc:mysql://mysql:3306/videodb
      - jdbc_user=orguser
      - jdbc_pass=secret1234
      - usercontext_header_name=X-Test-Auth

      - userattributes_role_key=UserRoles
      - userattributes_org_key=organisation

      - userrole_admin_values=adminrole
      - userrole_user_values=userrole1,userrole2
      - userrole_monitor_values=monitorrole
      - userrole_provisioner_values=provisionerrole
     depends_on:
      mysql:
       condition: service_healthy
   documenatation-and-test:
     image: kvalitetsit/medcom-video-api-documentation:latest
     environment:
      - BASE_URL=/test
     ports:
      - 80:8080
