# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
# Checkout source code
    - uses: actions/checkout@v2

    - name: echo
      env:
        GH: ${{ tojson(github) }}
      run: echo "$GH"

    - uses: olegtarasov/get-tag@v2
      id: tagName
      with:
        tagRegex: "v(.*)"  # Optional. Returns specified group text as tag name. Full tag string is returned if regex is not defined.
        tagRegexGroup: 1 # Optional. Default is 1.

    - name: Yet another step # Environment variabl usage example
      run: echo $GIT_TAG_NAME

      # Cache maven stuff
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

# Setup Java environment including maven
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 11

# Build solution. Also creates docker image.
    - name: Build with Maven
      run: mvn clean install

# Login to docker hub using secrets in GitHub.
    - name: Login to docker
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

# Tag image
    - name: Tag dev
      run: docker tag kvalitetsit/medcom-video-api:latest jonaspkit/video-api-test:dev

# Push to docker hub
    - name: Push to docker
      run: docker push jonaspkit/video-api-test:dev
  test:
    runs-on: ubuntu-latest
    steps:
      -  name: hej hej
         run: docker image ls
